# Generated by Django 4.1.5 on 2023-06-17 20:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=blog.models.upload_image_to),
        ),
    ]
